services:
  - type: web
    name: llmda-backend
    env: node
    buildCommand: npx prisma generate && npm install
    startCommand: npm run dev
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    plan: free
    region: ohio
